language: node_js
node_js:
  - '8'
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
cache:
  yarn: true
script:
  - yarn test
  - yarn run coveralls
