language: node_js
node_js:
  - '8'
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
cache: yarn
script:
  - yarn test
  - yarn run coveralls
deploy:
  provider: heroku
  api_key:
    secure: "NywKU5pGUW2RJ/NUWEQFpnU1LBGW0sYhUQTzhwk7JUI3G7r6TCFOUXfUIOi8c711zxM924qfy7Xq5g5arjipk0MVRYi3j/KDY2Kg8qLyP1JETx2p9qiEdmTXQnMJvl+VnsbzkAz6odPSudr5cnV4i13DN6IGkaYCt4rcM8I0GxgLQn+nxPFADaeOnWWVEHjSC4dDS8LuY6vrN7rpRw5udzYg6EBKJVHf/tY1mSy8PjZizRStDHH9Fx00II1uqA5+pJK3FijUnBsKDTt6KOHoG8qudBFYYrrvOw9RQd1ZFZmIucV2wyl770MxKNNGIH/U2o3etUTM+dEkoldcVhgBntSoj1PtojGzQK+f+6lvVFeFlVz+qOqfFMphebp5QJ8mt0+1DlbW7kZI82KZiQlBBLD46Ikn15KmvI0cqNe7HXQRQ6XMwJ3ZSQvl4ovuPN/QKNXCImEiDpqOhAch1M5KaM20VM2yT/Cc4cIl1Kwz66GBsGSSjj1OXtnT6sFIY15pVw5hV2aeDMk/Vh0ycJsLJPtsUklu+/BO/ncE+pESpStss0L85f+5kpcddUZQy9VqEUwnTBIV+Z8+zgB5NzZDlWp/GiL23TwORKevYpfjUlI9JgAWqAqp1nMX2xxX2SY21eWC0u0xQB3LmtU6wC9wyX15+GFv0arjVydUgceURjg="
