language: node_js
node_js:
- "8"
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
cache: yarn
script:
- yarn test
- yarn run coveralls
deploy:
  provider: heroku
  api_key:
    secure: LDnBp41UCLU//oQYyAk0u8klxcu0oWToSZ4nsEB5/2tP9cMk/9iOIfu29zFqKtvfXx+46pi2vfbY3oNbSMA15L2LjmX7WVg66jfOcChzASikbqKydD6VQKPdcTzbOu5YnKX1ZbIQSVU+bUUR5+0DO/1NAmgux4RABsHpqj+bu31XuIOC8bqQuOOfU5HTPGh46uwMhcyhFC+c/OYKlg1HrfxopZkbtarmX94lpNAMqP27Bqckv8/d2W5brXS/Y6cZEhZRpLjDauRMUe+4XNyZLPJiaE3XEJwaWb5SSeNSfC/6/VqFGF/FdSvalxBH85gBxq8ZIelq7eYXPl4b6kA4QbzxHXKRpb8A6aUpHS3JTRkUjXsAeldcLFCKIxR+HsuU4ceYNktipqimawAJRxbWKb7o6Fw0SaRxyKQ+HVbAii1HOIVb+thyI8bh8DBHBoDRv2MoOskgvttiOxa3RrFSnkU+VjDm2PHX1gdy1DceqOR2okf+6xP5spbJcF1c+hy0vXOUnVjm6uIEf4r21LnKKj75gvbWeDjNS7W6RAZmPmzNAtyk6p7KSHONNNpo/gUy2sCcaXmk3io4rRA5zwjipA/TFEkDpJtkTA4rsvrT2nvpR5x1iRD3HpopVy2vQAaEWr/J+DLiaNn+aQjODn5we/VxEL3VKQ/FX8bAOxE6Hgs=
  app: dariobattle
  on: 
    branch: master