version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/dariobattle
      - SESSION_SECRET=secret
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dariobattle
    volumes:
    # Les scripts qui sont dans le répertoire /docker-entrypoint-initdb.d/ sont exécutés à la création de la base de données
      - ./init-db:/docker-entrypoint-initdb.d
    # Pour conserver les données de la base de données entre chaque redémarrage du container on monte un volume
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: