CREATE TABLE users (
  login VARCHAR(255) PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  games INT DEFAULT 0 NOT NULL,
  kills INT DEFAULT 0 NOT NULL,
  deaths INT DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);